service: raffiner

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  clients:
    handler: bin/clients
    events:
      - http:
          path: clients
          method: get
      - http:
          path: clients
          method: post
      - http:
          path: clients
          method: put
      - http:
          path: clients
          method: delete