service: raffiner

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

environment:
  DB_ENDPOINT: "${file(env.json):DB_ENDPOINT}"
  DB_PORT: ${file(env.json):DB_PORT}
  DB_NAME: ${file(env.json):DB_NAME}
  DB_USERNAME: ${file(env.json):DB_USERNAME}
  DB_PASSWORD: ${file(env.json):DB_PASSWORD}

functions:
  clients:
    handler: bin/clients
    events:
      - http:
          path: clients
          method: get
      - http:
          path: clients
          method: post
      - http:
          path: clients
          method: put
      - http:
          path: clients
          method: delete
    environment:
      DB_ENDPOINT: "${file(env.json):DB_ENDPOINT}"
      DB_PORT: ${file(env.json):DB_PORT}
      DB_NAME: ${file(env.json):DB_NAME}
      DB_USERNAME: ${file(env.json):DB_USERNAME}
      DB_PASSWORD: ${file(env.json):DB_PASSWORD}
  suppliers:
    handler: bin/suppliers
    events:
      - http:
          path: suppliers
          method: get
      - http:
          path: suppliers
          method: post
      - http:
          path: suppliers
          method: put
      - http:
          path: suppliers
          method: delete
    environment:
      DB_ENDPOINT: "${file(env.json):DB_ENDPOINT}"
      DB_PORT: ${file(env.json):DB_PORT}
      DB_NAME: ${file(env.json):DB_NAME}
      DB_USERNAME: ${file(env.json):DB_USERNAME}
      DB_PASSWORD: ${file(env.json):DB_PASSWORD}
  products:
    handler: bin/products
    events:
      - http:
          path: products
          method: get
      - http:
          path: products
          method: post
      - http:
          path: products
          method: put
      - http:
          path: products
          method: delete
    environment:
      DB_ENDPOINT: "${file(env.json):DB_ENDPOINT}"
      DB_PORT: ${file(env.json):DB_PORT}
      DB_NAME: ${file(env.json):DB_NAME}
      DB_USERNAME: ${file(env.json):DB_USERNAME}
      DB_PASSWORD: ${file(env.json):DB_PASSWORD}